language: python
cache: pip
python:
  - "2.7.11"

before_install:
  - export DJANGO_SETTINGS_MODULE=kikar_hamedina.settings
  - export PYTHONPATH=$PYTHONPATH:$HOME/build/agamrafaeli/kikar-hamedina/kikar_hamedina

install: "pip install -r requirements/base.txt"

services: postgresql

before_script:
  # Prepare DB
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python kikar_hamedina/manage.py syncdb --noinput
  - wget https://s3-eu-west-1.amazonaws.com/kikar-dev/kikar_setup.db.gz
  - gunzip -c kikar_setup.db.gz | sudo -u postgres psql kikar

  # Run server
  - python kikar_hamedina/manage.py runserver localhost:8000 &
  - sleep 3
script:
  - nosetests
