language: python
cache: pip
python:
  - "2.7.11"

before_install:
  - export DJANGO_SETTINGS_MODULE=kikar_hamedina.settings
  - export PYTHONPATH=$PYTHONPATH:$HOME/builds/agamrafaeli/kikar-hamedina/kikar_hamedina

install: "pip install -r requirements/base.txt"
services: postgresql

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python kikar_hamedina/manage.py syncdb --noinput
  - python -c "import sys; print sys.path"
  - nosetests
